version: '3'
services:
  web:
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: .
    volumes:
      - .:/var/www/html